# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('version', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('seller', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
    ]
