# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0002_auction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
