# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0003_auto_20161106_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
