# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0004_auto_20161106_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(help_text='Enter the date like: dd/mm/yyyy'),
        ),
    ]
