# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0006_auto_20161106_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.IntegerField(default=1, help_text='Starting price'),
        ),
    ]
