# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0007_auto_20161107_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Starting price', max_digits=8),
        ),
    ]
