# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 19:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0009_auto_20161108_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='email',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 11, 19, 59, 41, 490482, tzinfo=utc), help_text='Enter the date like: YYYY-MM-DD HH:MM'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
