# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('YAAS', '0020_auto_20161108_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidobject',
            options={'ordering': ['bid']},
        ),
        migrations.AlterField(
            model_name='auction',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 11, 20, 47, 18, 247526, tzinfo=utc), help_text='Enter the date like: YYYY-MM-DD HH:MM'),
        ),
    ]
